# Generated by Django 5.0.4 on 2024-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=200)),
            ],
        ),
    ]
