# Generated by Django 5.0.4 on 2024-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logreport',
            name='session',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
