# Generated by Django 5.0.4 on 2024-05-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_logreport_device_remove_logreport_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logreport',
            name='session',
        ),
    ]
